### Get all coffees
GET http://localhost:8080/api/coffees

### Get coffee by id
GET http://localhost:8080/api/coffees/1

### Create coffee
POST http://localhost:8080/api/coffees
Content-Type: application/json

{
    "origin": "Ethiopia",
    "brewMethod": "FILTER"
}

### Update coffee
PUT http://localhost:8080/api/coffees/1
Content-Type: application/json

{
    "origin": "Colombia",
    "brewMethod": "ESPRESSO"
}

### Delete coffee
DELETE http://localhost:8080/api/coffees/1
