### GET request to example server
@eventId = 1
GET http://localhost:8080/api/events/{{eventId}}/participants
Authorization: Bearer {{token}}

###
@userId = 1
@eventToJoin = 1
POST http://localhost:8080/api/events/{{id}}/join
Authorization: Bearer {{token}}

###
@eventToLeave = 1
DELETE http://localhost:8080/api/events/{{eventToLeave}}/leave
Authorization: Bearer {{token}}
