### GET request to example server
@id =2
GET http://localhost:8080/api/events/{{id}}/participants

###
@userId =104
POST http://localhost:8080/api/events/{{id}}/join/{{userId}}

###
@eventIdToDelete = 4
DELETE http://localhost:8080/api/events/{{eventIdToDelete}}/leave
