###
GET http://localhost:8080/api/events/2/reviews

###
GET http://localhost:8080/api/events/2/reviews?page=1

###
GET http://localhost:8080/api/reviews/1

###
POST http://localhost:8080/api/events/2/reviews
Content-Type: application/json

{
    "rating": 2,
    "comment": ""
}

###
POST http://localhost:8080/api/events/4/reviews
Content-Type: application/json

{
    "rating": 5,
    "comment": ""
}

###
POST http://localhost:8080/api/events/4/reviews
Content-Type: application/json

{
    "rating": 9,
    "comment": ""
}

###
POST http://localhost:8080/api/events/999999/reviews
Content-Type: application/json

{
    "rating": 3,
    "comment": ""
}
