CREATE TABLE events
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    address TEXT,
    city TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    date_time TIMESTAMP,
    max_participants INTEGER,
    min_age INTEGER,
    max_age INTEGER,
    status VARCHAR(255) NOT NULL,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE event_tags
(
    event_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_event_tags PRIMARY KEY (event_id, tag_id),
    CONSTRAINT fk_event_tags_on_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_event_tags_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id)
);

