CREATE TABLE event_participation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT, FOREIGN KEY (event_id) references events(id),
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
