CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT not null,
    event_id BIGINT, FOREIGN KEY (event_id) references events(id),
    rating integer not null ,
    comment VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    UNIQUE (user_id, event_id)
);


