CREATE TABLE event
(
    id               BIGINT NOT NULL,
    title            VARCHAR(255),
    description      VARCHAR(255),
    address          VARCHAR(255),
    city             VARCHAR(255),
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION,
    date_time        TIMESTAMP WITHOUT TIME ZONE,
    max_participants INTEGER,
    min_age          INTEGER,
    max_age          INTEGER,
    status           SMALLINT,
    creator_id       BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE flag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    reason     VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_flag PRIMARY KEY (id)
);

ALTER TABLE flag
    ADD CONSTRAINT FK_FLAG_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);
