CREATE TABLE flag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    reason     VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_flag PRIMARY KEY (id)
);

ALTER TABLE flag
    ADD CONSTRAINT FK_FLAG_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);
